<?php defined('LINGER') || exit();?><!-- this file is generated by Linger! 2016/03/29 18:02:11 @author: liubang <it.liubang@qq.com> -->
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script type="text/javascript" src="/js/page/index.js"></script>
</head>
<body>
    <h1><?=$aaa?></h1>
    <h1><?php echo $aaa;?></h1>
    <ul>
        <?php foreach ($arr as $val) { ?>
            <li><?php echo $val['userId'];?> - <?php echo $val['userName'];?></li>
        <?php } ?>
    </ul>
</body>
</html>