<?php if(!defined('LINGER')){header('HTTP/1.1 403 Forbidden');die();}?><!-- this file is generated by Linger! 2016/03/30 11:28:40 @author: liubang <it.liubang@qq.com> -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>list page</div>
    <h1><?=$id?></h1>
</body>
</html>