<?php if(!defined('LINGER')){header('HTTP/1.1 403 Forbidden');die();}?><!-- this file is generated by Linger! 2016/03/31 16:06:35 @author: liubang <it.liubang@qq.com> -->
<footer>
    <div style="height: 30px; text-align:center">Powered By liubang</div>
</footer>