<?php defined('LINGER') || exit();?><!-- this file is generated by Linger! 2016/03/30 09:43:08 @author: liubang <it.liubang@qq.com> -->
<footer>
    <div style="height: 30px; text-align:center">Powered By liubang</div>
</footer>